import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'
import { cn } from '@/shared/lib/utils'
import { Toaster } from '@/shared/ui/toaster'
import { Header } from './header'
import { Providers } from './providers'

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
})
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={cn('grid grid-rows-[auto_1fr_auto] min-h-[100dvh]', geistSans.variable, geistMono.variable)}>
        <Providers>
          <Header />
          {children}
          <footer className="py-4 px-4">
            <p className="text-balance text-center text-sm leading-loose text-muted-foreground md:text-left">
              Built by{' '}
              <a
                href="https://github.com/EffectDoplera"
                target="_blank"
                rel="noreferrer"
                className="font-medium underline underline-offset-4"
              >
                EffectDoplera
              </a>
              . The source code is available on{' '}
              <a
                href="https://github.com/EffectDoplera/#"
                target="_blank"
                rel="noreferrer"
                className="font-medium underline underline-offset-4"
              >
                GitHub
              </a>
              .
            </p>
          </footer>
        </Providers>
        <Toaster />
      </body>
    </html>
  )
}
