import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'
import { TonConnectButton } from '@/features/connect-wallet'
import { cn } from '@/shared/lib/utils'
import { Toaster } from '@/shared/ui/toaster'
import Image from 'next/image'
import { Providers } from './providers'

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
})
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={cn('grid grid-rows-[auto_1fr_auto] min-h-[100dvh]', geistSans.variable, geistMono.variable)}>
        <Providers>
          <header className="p-4 sticky z-10 top-0 bg-slate-200 flex items-center justify-between">
            <div className="flex justify-between gap-1">
              <Image src="/toncoin-ton-logo.svg" alt="toncoin logo" width={30} height={30} priority />
              <p className="text-2xl font-bold uppercase">Ton Minter</p>
            </div>
            <TonConnectButton />
          </header>
          {children}
          <footer className="py-4 px-4">
            <p className="text-balance text-center text-sm leading-loose text-muted-foreground md:text-left">
              Built by{' '}
              <a
                href="https://github.com/EffectDoplera"
                target="_blank"
                rel="noreferrer"
                className="font-medium underline underline-offset-4"
              >
                EffectDoplera
              </a>
              . The source code is available on{' '}
              <a
                href="https://github.com/EffectDoplera/#"
                target="_blank"
                rel="noreferrer"
                className="font-medium underline underline-offset-4"
              >
                GitHub
              </a>
              .
            </p>
          </footer>
          <Toaster />
        </Providers>
      </body>
    </html>
  )
}
